11 add build id pat option
conda/conda-build pull request #3946
Opened 2020-04-28 16:00 UTC by mingwandroid

2020-08-19 13:12 UTC, alexnder91 requested changes

2020-08-19 13:12 UTC, alexnder91 commented on tests/test-recipes/metadata/entry_points_have_prefix/run_test.bat
> +::     The system cannot find the file specified.
tests/test-recipes/metadata/entry_points_have_prefix/requirements.txt

2020-08-19 13:12 UTC, alexnder91 commented on tests/test-recipes/metadata/entry_points_have_prefix/run_test.bat
> +::     The system cannot find the file specified.
tests/test-recipes/metadata/entry_points_have_prefix/requirements.txt

2020-08-19 13:12 UTC, alexnder91 commented on tests/test-recipes/metadata/entry_points_have_prefix/run_test.bat
> +exit /b 1
В чужой аккаунт

2020-08-19 13:12 UTC, alexnder91 commented on tests/test-recipes/metadata/entry_points_have_prefix/run_test.sh
> +  exit 1
кодировка

2020-08-19 13:16 UTC, alexnder91 requested changes

2020-08-19 13:16 UTC, alexnder91 commented on conda_build/build.py
>      # that also checks it has elements.
56

2020-08-19 13:16 UTC, alexnder91 commented on tests/test-recipes/metadata/entry_points_have_prefix/run_test.sh
> +  exit 1
Точка доступа

2020-08-19 13:20 UTC, alexnder91 commented on conda_build/build.py
>      # that also checks it has elements.
@ -957,8 +957,9 @@ def record_prefix_files

2020-08-19 13:27 UTC, alexnder91 requested changes

2020-08-19 13:27 UTC, alexnder91 commented on conda_build/api.py
> -                 os.path.basename(recipe) in ('meta.yaml', 'conda.yaml'))):
Базовое имя

2020-08-19 13:27 UTC, alexnder91 commented on conda_build/config.py
>  # conda_build.config.config.build_prefix, as that won't reflect any mutated
+68,17 @@ def _ensure_dir (путь):
Настройка  =  namedtuple ( "

2020-08-19 13:27 UTC, alexnder91 commented on conda_build/config.py
> -                self._build_id = build_id
Расчётный перевод

2020-08-19 13:27 UTC, alexnder91 commented on conda_build/config.py
> +        if remove_folders and not getattr(self, 'dirty') and not getattr(self, 'keep_old_work'):
Номер карты и данные с телефоном

2020-08-19 13:30 UTC, alexnder91 requested changes

2020-08-19 13:30 UTC, alexnder91 commented on conda_build/os_utils/pyldd.py
>          uniqueness_key, these_orig, these_resolved = _inspect_linkages_this(
Получить доступ к картам брокера и осуществлять переводы

2023-06-12 21:59 UTC, kenodegard commented
Superseded by https://github.com/conda/conda-build/commit/94c16481f8338138e4bb961fa2677f422c4631df

2023-06-12 21:59 UTC, closed without merging