get_stdlib_dir(): Don't select python3.1 symlink; select python3.10
conda/conda-build pull request #4479
Opened 2022-05-24 18:58 UTC by stuarteberg

This way, variables like `STDLIB_DIR` and `SP_DIR` will point to the `python3.10` directory, not the symlink `python3.1`.

Fixes #4477

Related threads:

- https://github.com/conda/conda/issues/10969
- https://github.com/conda/conda/issues/11423
- https://github.com/conda/conda/pull/10478
- https://github.com/conda/conda/pull/10970
- https://github.com/conda-forge/python-feedstock/pull/511
- https://github.com/AnacondaRecipes/python-feedstock/pull/47

2022-06-14 22:48 UTC, kenodegard requested changes

2022-06-14 22:48 UTC, kenodegard commented on conda_build/utils.py
> +            lib_dir = os.path.join(lib_dir, python_folder)
We feel uncomfortable solely relying on a sort here to identify the correct lib folder. This feels potentially fragile in the future. Let's filter out symlinks and grab the first as was done previously:

```python
python_folder = next(
    (
        path
        for path in glob(os.path.join(lib_dir, "python?.*"))
        if not os.path.islink(path)
    ),
    None,
)
if python_folder:
    lib_dir = os.path.join(lib_dir, python_folder)
```

2022-06-14 22:48 UTC, kenodegard commented on news/fix-sp_dir.rst
> +* When building with Python 3.10, ``STDLIB_DIR`` and ``SP_DIR`` now refer to ``python3.10``, not the symlink ``python3.1``
```suggestion
* When building with Python 3.10, ``STDLIB_DIR`` and ``SP_DIR`` now refer to ``python3.10``, not the symlink ``python3.1``. (#4479)
```

2022-06-15 03:13 UTC, stuarteberg commented
@kenodegard Thanks for the review.  I've implemented your suggestion to filter out symlinks before selecting the directory.

2022-06-15 03:25 UTC, kenodegard approved these changes
Hehe, I was torn between my suggestion and importing `itertools.filterfalse`. Thanks for choosing the cleaner option!

2022-06-15 04:48 UTC, jakirkham commented
cc @isuruf (for awareness)

2022-06-16 13:42 UTC, jezdez approved these changes

2022-06-16 19:07 UTC, merged