Updated broken example recipe links.
conda/conda-build pull request #4580
Opened 2022-09-14 15:47 UTC by tttc3

### Description
Updates some broken links to example conda recipes. Also adds a link to the conda-forge feedstocks and AnacondaRecipes aggregated feedstocks to replace the link to the now archived conda-recipes repo.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] ~~Add / update necessary tests?~~
- [x] Add / update outdated documentation?

2022-11-03 18:53 UTC, kathatherine requested changes
Thank you so much for this! Just one suggestion.

2022-11-03 18:53 UTC, kathatherine commented on docs/source/concepts/recipe.rst
> +The `conda-recipes <https://github.com/continuumio/conda-recipes>`_ repo,
```suggestion
The archived `conda-recipes <https://github.com/continuumio/conda-recipes>`_ repo,
```

2022-11-03 18:53 UTC, kathatherine commented on docs/source/concepts/recipe.rst
> +The `conda-recipes <https://github.com/continuumio/conda-recipes>`_ repo,
Should probably be clear it's an archive.

2022-11-04 21:22 UTC, kathatherine submitted a review, later dismissed
Thanks! Looks good to me.

2023-02-24 00:33 UTC, kenodegard commented on news/4580-update-broken-links
> +* Updated broken links to example conda recipes and updated link to the now archived conda-recipes, with additional links to AnacondaRecipes aggregated feedstocks and conda-forge feedstocks.
```suggestion
* Updated broken links to example conda recipes and updated link to the now archived conda-recipes, with additional links to AnacondaRecipes aggregated feedstocks and conda-forge feedstocks. (#4580)

```

2023-02-24 00:33 UTC, kenodegard approved these changes

2023-02-24 00:34 UTC, merged