Update disclaimer/LICENSE to reflect conda-build originally being part of conda
conda/conda-build pull request #4676
Opened 2022-12-15 23:29 UTC by kenodegard

### Description

We were reminded (https://github.com/conda/conda-build/pull/4568#issuecomment-1353773401) that conda-build's code was originally part of conda and only later (~2014) was it moved into a separate repo.

This change uses standard SPDX syntax for disclaimers (I opted to use `©`, if there are any objections or concerns I'll switch it back to `Copyright (c)`), credits Continuum Analytics with the original copyright, and recognizes the rename to Anaconda in 2017.

Sought to otherwise standardize the disclaimer and LICENSE.txt to mirror that of conda (PR with updates to conda's disclaimer and LICENSE.txt incoming).

Ref https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

2022-12-16 07:49 UTC, mbargull requested changes

2022-12-16 07:49 UTC, mbargull commented on .github/disclaimer.txt
> +SPDX-FileCopyrightText: © 2017 Anaconda, Inc. <https://www.anaconda.com>
Let's not overcomplicate things and go with
```suggestion
SPDX-FileCopyrightText: © 2012 Anaconda, Inc. <https://www.anaconda.com>
```
The copyright remained with the same entity ([CIK: 0001538860](https://www.sec.gov/edgar/browse/?CIK=0001538860)), after all.
Let's just us the current name.

2023-01-03 18:05 UTC, jezdez commented
Hmm, I wonder if https://hynek.me/til/copyright-years/ might be worth another look, a lot of corporate project have removed the years altogther!

2023-01-10 01:05 UTC, mbargull commented
> Hmm, I wonder if https://hynek.me/til/copyright-years/ might be worth another look, a lot of corporate project have removed the years altogether!

Ah, nice find! It's good to see that this is has some notable examples. That'd be my favored solution because it's more faithful, https://github.com/conda/conda-build/pull/4568#issuecomment-1353773401 :
> However, a lot of the code/source files are from 2016+, i.e., `(c) 2012`/`(c) 2014` is not representative/true for that.

Going with `SPDX-FileCopyrightText: © Anaconda, Inc. <https://www.anaconda.com>` in the file headers and either leaving `LICENSE.txt` untouched or just substituting Continuum -> Anaconda sounds reasonable.
(Though, I'd leave `2012` in `LICENSE.txt` -- doesn't really hurt at that single place, plus it is a faithful statement in there.)

2023-01-10 01:05 UTC, mbargull commented on .github/disclaimer.txt
> +SPDX-FileCopyrightText: © 2017 Anaconda, Inc. <https://www.anaconda.com>
```suggestion
SPDX-FileCopyrightText: © Anaconda, Inc. <https://www.anaconda.com>
```

2023-09-26 13:24 UTC, jezdez commented
No, this is blocked by the legal work being done in providing a trademark license to NumFOCUS and can now picked up again.

2024-10-26 04:03 UTC, closed without merging