Add R.dll to missing_dso_whitelist on windows
conda/conda-build pull request #4786
Opened 2023-02-24 16:32 UTC by isuruf

R.dll is in `lib/R/bin/x64` which is a non-standard directory and not in PATH. Usually on windows you either need the DLL to be on PATH or next to the downstream DLLs using the DLL. However R extensions (just like python extensions) are not loaded separately and are only loaded into a R session where R.dll is already loaded and therefore this warning is unnecessary. This fixes R recipes that errors when error_overlinking option is turned on

### Description

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-05-15 20:34 UTC, isuruf commented
ping

2023-06-05 11:49 UTC, jezdez approved these changes

2023-06-05 13:38 UTC, mfansler commented
While whitelisting is a useful stopgap to avoid these failures in linking analysis, might it be a better solution to have the linking analysis include the R library path by default? That would then also catch the cases where `libRblas.dll` or `libRlapack.dll` are linked, which similarly fail.

2024-01-25 09:14 UTC, jezdez requested changes
This needs at last a news file, a test (if possible). 

Besides, as I said elsewhere before, a ticket is needed so we can track the progress of bugs and features and account for regressions easier. The reason this keeps getting missed is that we're not considering PRs during issue sorting since PRs often don't have enough context for maintainers to work on it. Please be so kind to open a ticket first before submitting a PR.

2024-08-09 21:19 UTC, mfansler commented on conda_build/skeletons/cran.py
> +    - '*/R.dll'            # [win]
Same goes for `Rblas.dll` and `Rlapack.dll`, which are not infrequent.

```suggestion
    - '*/R.dll'            # [win]
    - '*/Rblas.dll'        # [win]
    - '*/Rlapack.dll'      # [win]
```

2025-09-10 04:03 UTC, closed without merging