Deprecate `ns_cfg()` in `metadata.py`
conda/conda-build pull request #4837
Opened 2023-03-30 19:26 UTC by beeankha

Deprecating the `ns_cfg()` function in favor of `get_selectors()`. Also adding type hinting.

2023-03-31 19:59 UTC, beeankha commented
pre-commit.ci autofix

2023-04-06 15:57 UTC, kenodegard requested changes

2023-04-06 15:57 UTC, kenodegard commented on conda_build/metadata.py
> +    )
```suggestion
    data = select_lines(
        data,
        get_selectors(config),
        variants_in_place=bool(config.variant),
    )
```

2023-04-06 15:58 UTC, kenodegard approved these changes

2023-04-07 18:03 UTC, merged