Cleanup
conda/conda-build pull request #4843
Opened 2023-04-06 21:08 UTC by ryanskeith

### Description

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-04-07 02:02 UTC, kenodegard requested changes
Minor word smithing

2023-04-07 20:13 UTC, kenodegard commented on conda_build/index.py
> +        cache_path.mkdir(exist_ok=True)
`os.makedirs(path)` == `Path(path).mkdir(parents=True)`

```suggestion
        cache_path.mkdir(parents=True, exist_ok=True)
```

2023-04-07 20:14 UTC, kenodegard approved these changes

2023-04-10 14:30 UTC, dholth commented on conda_build/config.py
> -# Python2 silliness:
it's only a model

2023-04-12 04:18 UTC, merged