Only collect dsos for files that will be inspected
conda/conda-build pull request #4951
Opened 2023-07-28 17:47 UTC by tl-hbk

### Description

This PR fixes the issue mentioned in https://github.com/conda/conda-build/issues/4944

After going through `post.py` and looking at where `all_needed_dsos` and `needed_dsos_for_file` are used, I think that it isn't necessary to collect dsos for non platform specific types.  

As I mentioned in the github issue, at the beginning of `check_overlinking_impl`, there is a check to filter for only files for whatever platform is being built

```
    files_to_inspect = []
    filesu = []
    for f in files:
        path = join(run_prefix, f)
        filetype = codefile_type(path)
        if filetype and filetype in filetypes_for_platform[subdir.split("-")[0]]:
            files_to_inspect.append(f)
        filesu.append(f.replace("\\", "/"))

    if not files_to_inspect:
        return dict()
```

Later in the code after `all_needed_dsos, needed_dsos_for_file = _collect_needed_dsos(...)` is called, `needed_dsos_for_file ` is only used in a loop that checks against the filtered files.

```
    for f in files_to_inspect:
        needed = needed_dsos_for_file[f]
```

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-01-24 20:27 UTC, tl-hbk commented
@kenodegard sorry if you're not the right person to ping for this but I was wondering if someone could take a look at this PR and the issue associated.

2025-04-28 10:28 UTC, beckermr requested changes
This appears to be safe to merge, but it does need a test.

2025-04-28 11:40 UTC, beckermr commented
@tl-hbk Can you point me to original package build where you found this error?I see your github with the reproducer, but I'd like to look at the upstream package directly.

2025-04-28 13:01 UTC, tl-hbk commented
There wasn't a public feedstock where this happened.  It occured in a build for an internal package at my employer.

2025-04-28 13:06 UTC, tl-hbk commented
Sure I'll try to add that for a test.

2026-05-29 05:25 UTC, closed without merging