Add support for Python 3.12
conda/conda-build pull request #4998
Opened 2023-09-07 15:32 UTC by johnnynunez

#4997
- Python 3.8 deprecation (https://devguide.python.org/versions/)
<img width="776" alt="image" src="https://github.com/conda/conda/assets/22727137/7a622a9c-7965-4d4a-8b4b-43fd3579f931">

2023-12-07 17:59 UTC, kenodegard requested changes

2023-12-07 17:59 UTC, kenodegard commented on .github/workflows/tests.yml
> +        python-version: ['3.9']
Python 3.8 is still our lower bound

```suggestion
        python-version: ['3.8']
```

2023-12-07 17:59 UTC, kenodegard commented on .github/workflows/tests.yml
> +        python-version: ['3.9']
```suggestion
        python-version: ['3.8']
```

2023-12-07 17:59 UTC, kenodegard commented on pyproject.toml
>    "Programming Language :: Python :: 3.9",
```suggestion
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
```

2023-12-07 17:59 UTC, kenodegard commented on tests/test_variants.py
> +    } == {"python >=3.10,<3.12.0a0", "python >=3.12,<3.13.0a0"}
```suggestion
    } == {"python >=3.10,<3.11.0a0", "python >=3.11,<3.12.0a0", "python >=3.12,<3.13.0a0"}
```

2023-12-07 17:59 UTC, kenodegard commented on tests/test_api_render.py
> +    python_versions = ["2.6", "3.4", "3.11", "3.12"]
```suggestion
    python_versions = ["2.6", "3.4", "3.11"]
```

2023-12-07 17:59 UTC, kenodegard commented on tests/test_api_render.py
> +    assert "foo >=3.10.0.rc1,<3.12.0a0" in m.meta["requirements"]["run"]
```suggestion
    assert "foo >=3.10.0.rc1,<3.11.0a0" in m.meta["requirements"]["run"]
```

2023-12-07 17:59 UTC, kenodegard commented on tests/test_api_render.py
> +    assert "python >=3.10.0rc1,<3.12.0a0" in m.meta["requirements"]["run"]
```suggestion
    assert "python >=3.10.0rc1,<3.11.0a0" in m.meta["requirements"]["run"]
```

2023-12-07 17:59 UTC, kenodegard commented on recipe/conda_build_config.yaml
>    - 3.9
```suggestion
  - 3.8
  - 3.9
```

2023-12-07 18:11 UTC, kenodegard commented
pre-commit.ci autofix

2024-01-09 18:35 UTC, kenodegard commented
Ugh, the https://github.com/conda/conda_build_test_recipe repo needs updating for Python 3.12 support...

2024-01-09 23:49 UTC, kenodegard commented on conda_build/skeletons/pypi.py
> +    distutils = join(stdlib_dir, "distutils")
```suggestion
    # distutils deprecated in Python 3.10+, removed in Python 3.12+
    distutils = join(stdlib_dir, "distutils")
```

2024-01-09 23:49 UTC, kenodegard commented on tests/requirements.txt
> +conda-forge::anaconda-client
Revert since `anaconda-client` is now available on `main`:

```suggestion
anaconda-client
beautifulsoup4
chardet
conda >=22.11.0
```

2024-01-10 18:45 UTC, kenodegard approved these changes

2024-01-10 19:21 UTC, jezdez approved these changes

2024-01-10 19:23 UTC, merged