Bugfix: avoid clobbering of high priority cbc.yaml entries by lower ones
conda/conda-build pull request #5039
Opened 2023-10-16 21:05 UTC by danpetry

### Description

Fixes https://github.com/conda/conda-build/issues/5038

When higher priority cbc.yamls contain, for a certain config entry, a superset of values that are in a lower priority cbc.yaml, the extra values get ignored. For example, if you have in a feedstock's conda_build_config.yaml

```
openssl:
  - 1.1.1
  - 3.0
```

and in aggregate/conda_build_config.yaml

```
openssl:
  - 3.0
```

I would expect two versions of the package is build, but only the one with openssl 3.0 is built.

When a `zip_keys` entry is used in the feedstock's cbc.yaml, the keys get zipped, but then the variants without the entry from the aggregate cbc.yaml gets clobbered.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-10-17 14:13 UTC, travishathaway commented
@conda-bot check

2023-10-26 16:44 UTC, danpetry commented
Hi @travishathaway or @kenodegard or other? It would be nice to get some eyes on this if possible - we're affected by this relatively frequently in the packaging team

2023-10-27 14:20 UTC, danpetry commented on conda_build/variants.py
> +    )  # seen_keys makes sure that a setting from a lower-priority spec doesn't clobber the same setting that has been redefined in a higher-priority spec.
agreed, the pre-commit checks told me to do this though.

2023-11-02 15:30 UTC, kenodegard requested changes

2023-11-02 15:30 UTC, kenodegard commented on tests/test_variants.py
> +    )
no need to use `OrderedDict` anymore:

```suggestion
    combined_spec = {
        **low_prio_config,
        **high_prio_config,
    }
    specs = {
        "internal_defaults": internal_defaults,
        "low_prio_config": low_prio_config,
        "high_prio_config": high_prio_config,
    }
```

2023-11-02 15:30 UTC, kenodegard commented on tests/test_variants.py
> +        ),
```suggestion
        pytest.param(
            {"pkg_1": "1.0"},
            {"pkg_1": "1.1"},
            {"pkg_1": ["1.1", "1.2"], "pkg_2": ["1.1"]},
            [{"pkg_1": "1.1", "pkg_2": "1.1"}, {"pkg_1": "1.2", "pkg_2": "1.1"}],
            id="basic",
        ),
```

2023-11-02 15:30 UTC, kenodegard commented on tests/test_variants.py
> +        ),
```suggestion
        pytest.param(
            {"pkg_1": "1.0"},
            {"pkg_1": "1.1"},
            {
                "pkg_1": ["1.1", "1.2"],
                "pkg_2": ["1.1", "1.2"],
                "zip_keys": [["pkg_1", "pkg_2"]],
            },
            [
                {"pkg_1": "1.1", "pkg_2": "1.1", "zip_keys": [["pkg_1", "pkg_2"]]},
                {"pkg_1": "1.2", "pkg_2": "1.2", "zip_keys": [["pkg_1", "pkg_2"]]},
            ],
            id="zip_keys",
        ),
```

2023-11-02 15:31 UTC, kenodegard approved these changes

2023-11-02 15:52 UTC, danpetry commented
Thanks @kenodegard ! how many approvals required to merge?

2023-11-02 18:57 UTC, merged