Adding conda-sphinx-theme to conda-build 3.27.x
conda/conda-build pull request #5073
Opened 2023-11-15 12:01 UTC by travishathaway

### Description

Fixes: #5061 

This is the pull request for the 3.27.x branch.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-11-15 22:38 UTC, kathatherine submitted a review, later dismissed
LGTM as a first step

2023-11-27 22:29 UTC, kenodegard requested changes

2023-11-27 22:29 UTC, kenodegard commented on docs/source/conf.py
> +# html_style = "css/custom.css"
Delete `custom.css` too as is done in https://github.com/conda/conda-build/pull/5067?

2023-11-27 22:29 UTC, kenodegard commented on docs/source/resources/compiler-tools.rst
> +
Not released yet (https://github.com/conda/conda-build/commit/e2916a2a5c590382323de97da6ac2fe6c516ff89):

```suggestion
```

2023-11-27 22:29 UTC, kenodegard commented on docs/source/resources/define-metadata.rst
> +     - True if the platform is either macOS or Linux or emscripten.
Not released yet (https://github.com/conda/conda-build/commit/d480c32597d7cb986ec89dbc8152d474b627e404)

2023-11-27 22:29 UTC, kenodegard commented on docs/source/resources/define-metadata.rst
> +
Not released yet (https://github.com/conda/conda-build/commit/d480c32597d7cb986ec89dbc8152d474b627e404)

2023-11-28 16:48 UTC, kenodegard approved these changes

2023-11-28 16:50 UTC, merged