Adding goat counter and bumping docs theme version
conda/conda-build pull request #5093
Opened 2023-12-01 14:36 UTC by travishathaway

### Description

xref: https://github.com/conda/conda-docs/issues/905

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [x] Add / update outdated documentation?

2023-12-01 17:34 UTC, kenodegard commented on docs/requirements.txt
> +conda-sphinx-theme==0.1.3
In conda we don't pin at all, should that change?

https://github.com/conda/conda/blob/d891d9f59f193a3e28bf28c959f41b08e304f31c/docs/requirements.txt#L1

2023-12-04 09:10 UTC, jezdez requested changes

2023-12-05 14:01 UTC, travishathaway commented on docs/source/_templates/layout.html
> +        async src="//gc.zgo.at/count.js"></script>
Good idea. I had forgotten that we did something similar for conda-dot-org.

2023-12-06 16:26 UTC, jezdez commented on docs/source/_templates/layout.html
> +        async src="_static/js/count.js"></script>
I think that's not needed anymore?

2023-12-06 17:35 UTC, travishathaway commented on docs/source/_templates/layout.html
> +        async src="_static/js/count.js"></script>
oops

2023-12-06 17:35 UTC, travishathaway commented on docs/source/_templates/layout.html
> +        async src="_static/js/count.js"></script>
removing

2023-12-06 18:00 UTC, jezdez approved these changes

2023-12-06 18:00 UTC, merged