allow LIEF to fail when using patchelf
conda/conda-build pull request #5176
Opened 2024-02-09 13:30 UTC by minrk

avoids unconditional failure when LIEF raises, even when not used

### Description

related to #5175, this allows LIEF to fail just like patchelf.

Previously, even when specifying `method=patchelf`, LIEF was unconditionally run. This adds error handling matching patchelf, so errors in an unused method don't prevent proceeding with patchelf.

2024-06-10 16:41 UTC, beeankha requested changes
Hi @minrk , thank you so much for this PR! A few things are requested (or are open for discussion) prior to merge:

1. Is there any way that this code could be re-worked to use `log.warn` / `log.error` (with `log = utils.get_logger(__name__)`) for the error handling? I understand that you most likely wanted to remain consistent with the rest of the `mk_relative_linux` function, but we can take this opportunity to improve error handling patterns (if you feel inclined to do so!)

2. It would be great to see a test or two for this change; addtionally it might help to have more details in the PR description for steps on how to reproduce LIEF being unconditionally run even when `method=patchelf` was specified

3. Please add a news file with a brief description of this change

2024-06-21 09:22 UTC, minrk commented
I switched it to log and added news. I'm afraid I don't know how to exercise this failure in a test.

2024-06-28 13:36 UTC, beeankha commented on news/5176-lief-fail
> +* Error handling when LIEF fails is now consistent with patchelf
```suggestion
* Error handling when `LIEF` fails is now consistent with `patchelf`. (#5176)
```

2024-06-28 17:13 UTC, beeankha submitted a review, later dismissed

2024-07-12 07:24 UTC, jaimergp commented
Hm, the modified function is now using two different methods to report errors and warnings to the user. This implies slightly different formats, and also different streams (logging will print to stderr and print to stdout, as currently configured). I'd rather stick to one of the methods so:

- Either change everything to logging (and move `logger` to the top-level module namespace, under the imports)
- Revert to print with the same format as the other messages. We would need to create an issue to tackle a general move to logging, if one doesn't exist yet

2024-07-15 20:22 UTC, beeankha commented
Per Jaime's [comment,](https://github.com/conda/conda-build/pull/5176#issuecomment-2224985028) I reverted the logging changes; I also went ahead and [filed an issue](https://github.com/conda/conda-build/issues/5415) to change all error-reporting to logging.

2024-07-15 20:38 UTC, dholth approved these changes

2024-07-16 04:12 UTC, merged