Removal deprecated function: get_output_file_path
conda/conda-build pull request #5208
Opened 2024-03-01 21:14 UTC by ryanskeith

### Description

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

2024-03-07 16:43 UTC, beeankha commented
pre-commit.ci autofix

2024-03-08 00:11 UTC, ryanskeith commented
Do we feel okay with doing this deprecation without using the @deprecated function?  @beeankha @kenodegard  I feel we are ok as users have been warned for the last 7 years, but would be perfectly fine backtracking.  The only internal use we have is for the tests.  Everywhere else has been using the newer name.

2024-03-08 16:31 UTC, ryanskeith commented
Will do.

2024-03-08 17:21 UTC, kenodegard requested changes

2024-03-08 17:21 UTC, kenodegard commented on conda_build/api.py
>  from .config import Config, get_channel_urls, get_or_merge_config
The deprecations module is also available in conda-build:

```suggestion
# make the Config class available in the api namespace
from .config import DEFAULT_PREFIX_LENGTH as _prefix_length
from .config import Config, get_channel_urls, get_or_merge_config
from .deprecations import deprecated
```

2024-03-08 17:21 UTC, kenodegard commented on news/5208-deprecate-get_output_file_path
> +* Mark `conda_build.api.get_output_file_path` as deprecated. (#5208)
```suggestion
* Mark `conda_build.api.get_output_file_path` as deprecated. Use `conda_build.api.get_output_file_paths` instead. (#5208)
```

2024-03-08 17:22 UTC, kenodegard approved these changes

2024-03-08 17:27 UTC, beeankha approved these changes

2024-03-08 23:03 UTC, merged