Inline `MetaData` ordering when dumping to yaml
conda/conda-build pull request #5282
Opened 2024-04-12 21:06 UTC by kenodegard

### Description

Simplified `conda_build.render.output_yaml` to avoid the most costly `MetaData.copy` and to eliminate the need for special customizations of the yaml engine.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

2025-04-17 09:52 UTC, jezdez requested changes
Needs an update to the deprecation statements

2025-04-18 15:30 UTC, kenodegard commented on conda_build/render.py
> +@deprecated("24.5", "24.7")
```suggestion
@deprecated("25.5", "25.7")
```

2025-04-18 15:30 UTC, kenodegard commented on conda_build/render.py
> +@deprecated("24.5", "24.7")
```suggestion
@deprecated("25.5", "25.7")
```

2025-04-18 15:30 UTC, kenodegard commented on conda_build/render.py
> +@deprecated("24.5", "24.7")
```suggestion
@deprecated("25.5", "25.7")
```

2025-04-18 15:30 UTC, kenodegard commented on conda_build/render.py
> +@deprecated("24.5", "24.7")
```suggestion
@deprecated("25.5", "25.7")
```

2025-04-18 18:57 UTC, beckermr commented on conda_build/render.py
> -        Dumper=_IndentDumper,
What did the _IndentDumper do?

2025-04-21 15:24 UTC, kenodegard commented on conda_build/render.py
> -        Dumper=_IndentDumper,
Looks like it forced an extra indent level:

```
build:
  entry_points:
    - conda-build: conda_build.cli.main_build:execute
    - conda-convert: conda_build.cli.main_convert:execute
    - conda-debug: conda_build.cli.main_debug:execute
    - conda-develop: conda_build.cli.main_develop:execute
    - conda-inspect: conda_build.cli.main_inspect:execute
    - conda-metapackage: conda_build.cli.main_metapackage:execute
    - conda-render: conda_build.cli.main_render:execute
    - conda-skeleton: conda_build.cli.main_skeleton:execute
  script: '{{ PYTHON }} -m pip install . -vv'
```

```
build:
  entry_points:
  - conda-build: conda_build.cli.main_build:execute
  - conda-convert: conda_build.cli.main_convert:execute
  - conda-debug: conda_build.cli.main_debug:execute
  - conda-develop: conda_build.cli.main_develop:execute
  - conda-inspect: conda_build.cli.main_inspect:execute
  - conda-metapackage: conda_build.cli.main_metapackage:execute
  - conda-render: conda_build.cli.main_render:execute
  - conda-skeleton: conda_build.cli.main_skeleton:execute
  script: '{{ PYTHON }} -m pip install . -vv'
```

I'll tinker a little more and see if I can get the indent a different way

2025-04-21 15:32 UTC, beckermr commented on conda_build/render.py
> -        Dumper=_IndentDumper,
This SO post might help: https://stackoverflow.com/questions/60226848/array-does-not-have-indent-or-space-in-pyyaml.

2025-04-21 15:36 UTC, kenodegard commented on conda_build/render.py
> -        Dumper=_IndentDumper,
also found this: https://github.com/yaml/pyyaml/issues/234

all of the suggested solutions are variants of our `_IndentDumper`

so if we stick with PyYAML we should keep the `_IndentDumper` after all

2025-04-21 15:55 UTC, kenodegard commented on news/5282-remove-custom-yaml
> +* Deprecate `conda_build.render._IndentDumper`. Unused.  (#5282)
```suggestion
* Deprecate `conda_build.render._IndentDumper`. Use `conda_build.render.CustomDumper` instead.  (#5282)
```

2025-04-21 16:54 UTC, kenodegard commented on conda_build/render.py
> -        Dumper=_IndentDumper,
Renamed `_IndentDumper` to `CustomDumper` since it did more than indentations, see https://github.com/conda/conda-build/pull/5282/commits/f1ee73277316f76172eb5a0921dcff04591c8edb

2025-04-21 17:32 UTC, beckermr approved these changes

2025-05-09 07:58 UTC, jezdez approved these changes

2025-05-09 07:59 UTC, merged