`sys.exit` removals from `build.py`
conda/conda-build pull request #5402
Opened 2024-07-09 19:41 UTC by beeankha

### Description

Replacing `sys.exit` call in`conda_build/build.py` with the new `CondaBuildUserError` exception for better error handling, along with corresponding unit tests. Removed redundant code from `post_process_files()` function, which included a `sys.exit` call.

The changes in this PR are separated out from work previously done by @kenodegard in #5255
Xref #4209 

### Checklist - did you ...

- [ ] ~~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~~
     
- [ ] Add / update necessary tests?
- [ ] ~~Add / update outdated documentation?~~

2024-07-11 15:36 UTC, kenodegard requested changes
We need to add tests checking for these exceptions being raised

2024-07-11 15:37 UTC, beckermr submitted a review, later dismissed

2024-07-11 20:05 UTC, kenodegard commented on conda_build/build.py
> +        CondaBuildUserError(
Oops missing `raise`!

```suggestion
        raise CondaBuildUserError(
```

2024-07-12 15:40 UTC, kenodegard approved these changes

2024-07-12 16:43 UTC, merged