Prefer sysroot matching subdir when there are multiple
conda/conda-build pull request #5404
Opened 2024-07-11 05:59 UTC by isuruf

### Description

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

       
Fixes https://github.com/conda/conda-build/issues/5403

2024-07-12 02:41 UTC, h-vetinari commented
I tested this PR in https://github.com/conda-forge/matplotlib-feedstock/pull/398 and it works! Great work!

2024-07-12 15:39 UTC, kenodegard requested changes
@isuruf I see this is still in draft mode, if you're not ready for reviews feel free to ignore these comments

2024-07-12 15:39 UTC, kenodegard commented on conda_build/post.py
> +            path = os.path.dirname(path)
It looks like all of the paths will end with `/`, see line 1374 above:

```python
srs = sysroot if sysroot.endswith("/") else sysroot + "/"
```

So we can simplify this and remove the conditional

2024-07-12 15:39 UTC, kenodegard commented on conda_build/post.py
> +    def sysroot_matches_subdir(path):
Let's include a comment here with an example of what the `sysroot` path will look like. Make it easier to understand what we are slicing out of the pathname.

2024-07-12 21:26 UTC, kenodegard approved these changes
Minor suggestion, otherwise LGTM!

2024-07-12 21:26 UTC, kenodegard commented on conda_build/post.py
> +        return triplet.split("-")[0] == GNU_ARCH_MAP.get(subdir_arch, subdir_arch)
```suggestion
        sysroot_arch = Path(path).parent.name.split("-")[0]
        subdir_arch = subdir.split("-")[-1]
        return sysroot_arch == GNU_ARCH_MAP.get(subdir_arch, subdir_arch)
```

2024-07-12 21:41 UTC, kenodegard approved these changes

2024-07-13 14:02 UTC, beeankha approved these changes

2024-07-15 14:29 UTC, merged

2024-09-03 18:43 UTC, kenodegard commented
`tests/test_api_build.py::test_sysroots_detection` implemented here is now failing on `main`, see https://github.com/conda/conda-build/actions/runs/10671805383/job/29578195906