Fix run export substring check
conda/conda-build pull request #5575
Opened 2024-12-31 20:46 UTC by vyasr

### Description

This PR fixes #5529.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda-build/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [ ] ~Add / update outdated documentation?~

2024-12-31 20:49 UTC, vyasr commented
I just signed the CLA. Let me know if I need to forward the confirmation email to anyone.

2024-12-31 20:55 UTC, vyasr commented
One note that isn't directly related to this PR but did affect me is that the [test requirements file](https://github.com/conda/conda-build/blob/main/tests/requirements.txt) is also missing a few additional requirements.
- pytest: This one should definitely be there to run the tests. I do see it in the requirements-ci.txt file, but I'm not sure what the purpose of requirements.txt is if not to include everything needed to at least run the tests locally as well.
- pytest-cov: This probably shouldn't be a hard requirement, but it currently is due to the [hardcoded addopts in pyproject.toml](https://github.com/conda/conda-build/blob/main/pyproject.toml#L96).
- binstar_client: I guess this is [a legacy pre-anaconda project](https://binstar-client.readthedocs.io/en/latest/), so I'm not sure where it should be coming from or if it should still be used here.

2024-12-31 21:38 UTC, vyasr commented
I also need a bit of help figuring out the right way to test this. I've verified the result manually, but I couldn't find an easy programmatic way of doing this with conda_build APIs since rendering isn't sufficient so we can't just inspect metadata. The best I could come up with is running the build and then manually extracting and inspecting the metadata of the result. I'm not sure if there is a better way, though.

2025-01-01 20:32 UTC, tkelman commented on tests/requirements.txt
> +py-lief <0.15
#5565 should make this unnecessary

2025-01-02 17:26 UTC, vyasr commented on tests/requirements.txt
> +py-lief <0.15
Depending on when PRs get reviewed happy to remove this change or switch up the merge order as is convenient.

2025-01-02 17:26 UTC, vyasr commented
@conda-bot check

2025-01-02 21:04 UTC, tkelman commented on tests/requirements.txt
> +py-lief <0.15
Likewise, I could merge or rebase on main and undo this inside #5565 if this gets merged first. Defer to maintainers on what order they'd rather merge in.

2025-01-10 23:08 UTC, vyasr commented
The test failures look completely unrelated to my change, but I do still need some help with the things I listed above before this PR would be ready.

2025-01-25 04:56 UTC, vyasr commented on tests/requirements.txt
> +py-lief <0.15
Removing this change since #5565 merged.
```suggestion
py-lief
```

2025-01-25 04:56 UTC, vyasr commented on tests/requirements.txt
> +py-lief <0.15
I removed this pinning now that your PR is in. Thanks!

2025-02-14 12:36 UTC, beckermr requested changes
The test needs to check that the run deps of the package are correct in addition to ensuring that the package builds.

2025-02-16 19:14 UTC, vyasr commented
> The test needs to check that the run deps of the package are correct in addition to ensuring that the package builds.

Thanks for taking a look @beckermr. I had [some questions above about how to test](https://github.com/conda/conda-build/pull/5575#issuecomment-2566721725), could you please provide some guidance?

2025-02-16 19:23 UTC, beckermr commented
Yes. Running the build and then manually testing the resulting package is perfectly fine.

2025-02-27 17:51 UTC, beckermr approved these changes

2025-02-27 17:52 UTC, beckermr commented
The rendered recipe is printed to stdout, so I added a check for the correct run export there.

2025-02-27 18:24 UTC, beckermr commented
ack only conda-forge outputs the python_abi package.

2025-02-27 18:45 UTC, beckermr approved these changes

2025-02-27 18:46 UTC, beckermr commented
windows failures are unrelated and appear to be a network outage - will rerun.

2025-02-27 20:14 UTC, merged

2025-02-28 05:15 UTC, vyasr commented
@beckermr thanks for finishing this up for me! I meant to get back to it but hadn't quite gotten around to it quite yet. I appreciate the assist!